### ISSUE TITLE
sorting funtion 완료

### ISSUE THREAD

**Issue by jeeseongmin** [ykeab94/oss_teamproject#9]
정렬 함수 구현 완료했습니다!
정렬 기준은 
이름, 중간고사, lab, project, 기말고사입니다.

테스트 해보시고 수정사항 있으면 말씀해주세요~!

**Comment by ykeab94** [comment]
네 테스트 해보았을때 중간고사, lab, project, 기말고사 기준 정렬은 잘 작동하였고 
이름 기준으로 정렬하려고 할때

![image](https://user-images.githubusercontent.com/63792404/81924450-1db5ef00-961a-11ea-9586-29a25d54abeb.png)

위에 그림과 같이 출력결과 1번에 0 0 0 0 이 출력되는 오류를 발견하였습니다!

**Comment by jeeseongmin** [comment]
수정해서 PR 보냈습니다!!
확인해주세요~~!!

**Comment by ykeab94** [comment]
네 확인했습니다 감사합니다!
